included: # paths to include during linting. `--path` is ignored if present.
  - bamzon
  - bamzonTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace # will try to implement this after fixing xcode
  - todo
  - function_body_length
