# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'bamzon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bamzon
  pod 'JTAppleCalendar', '~> 7.0'
  pod 'XLPagerTabStrip', '~> 8.1'

end
